// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oboete.Database;

namespace Oboete.Database.Migrations
{
    [DbContext(typeof(OboeteContext))]
    [Migration("20180628115001_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Oboete.Database.Entity.Deck", b =>
                {
                    b.Property<int>("DeckID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeckName")
                        .IsRequired();

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.HasKey("DeckID");

                    b.HasIndex("DeckName")
                        .IsUnique();

                    b.ToTable("Deck");

                    b.HasData(
                        new { DeckID = 1, CreatedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 811, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), DeckName = "Default Deck", ModifiedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 811, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Oboete.Database.Entity.Flashcard", b =>
                {
                    b.Property<int>("FlashCardID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("EaseFactor");

                    b.Property<int>("FlashcardTemplateID");

                    b.Property<int>("IntervalIndex");

                    b.Property<DateTimeOffset>("LastReviewDateTime");

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.Property<DateTimeOffset>("NextReviewDateTime");

                    b.Property<int>("NoteID");

                    b.HasKey("FlashCardID");

                    b.HasIndex("FlashcardTemplateID");

                    b.HasIndex("NoteID");

                    b.ToTable("Flashcard");
                });

            modelBuilder.Entity("Oboete.Database.Entity.FlashcardTemplate", b =>
                {
                    b.Property<int>("FlashcardTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardBackTemplate");

                    b.Property<string>("CardFrontTemplate");

                    b.Property<string>("CardStyling");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FlashcardTemplateName")
                        .IsRequired();

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.Property<int>("NoteTypeID");

                    b.HasKey("FlashcardTemplateID");

                    b.HasIndex("NoteTypeID", "FlashcardTemplateName")
                        .IsUnique();

                    b.ToTable("FlashcardTemplate");

                    b.HasData(
                        new { FlashcardTemplateID = 1, CardBackTemplate = "{{Back}}", CardFrontTemplate = "{{Front}}", CardStyling = "", CreatedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 815, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), FlashcardTemplateName = "Default Flashcard", ModifiedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 815, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), NoteTypeID = 1 }
                    );
                });

            modelBuilder.Entity("Oboete.Database.Entity.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DeckID");

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.Property<int>("NoteTypeID");

                    b.HasKey("NoteID");

                    b.HasIndex("DeckID");

                    b.HasIndex("NoteTypeID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Oboete.Database.Entity.NoteType", b =>
                {
                    b.Property<int>("NoteTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NoteTypeName")
                        .IsRequired();

                    b.HasKey("NoteTypeID");

                    b.HasIndex("NoteTypeName")
                        .IsUnique();

                    b.ToTable("NoteType");

                    b.HasData(
                        new { NoteTypeID = 1, NoteTypeName = "Default Note" }
                    );
                });

            modelBuilder.Entity("Oboete.Database.Entity.NoteTypeFieldDefinition", b =>
                {
                    b.Property<int>("NoteTypeFieldDefinitionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.Property<string>("NoteFieldDisplay")
                        .IsRequired();

                    b.Property<string>("NoteFieldName")
                        .IsRequired();

                    b.Property<int>("NoteTypeID");

                    b.Property<int>("SequenceID");

                    b.HasKey("NoteTypeFieldDefinitionID");

                    b.HasIndex("NoteTypeID", "NoteFieldName")
                        .IsUnique();

                    b.HasIndex("NoteTypeID", "SequenceID")
                        .IsUnique();

                    b.ToTable("NoteTypeFieldDefinition");

                    b.HasData(
                        new { NoteTypeFieldDefinitionID = 1, CreatedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 814, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), ModifiedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 814, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), NoteFieldDisplay = "Front", NoteFieldName = "Front", NoteTypeID = 1, SequenceID = 1 },
                        new { NoteTypeFieldDefinitionID = 2, CreatedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 814, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), ModifiedDateTime = new DateTimeOffset(new DateTime(2018, 6, 28, 11, 50, 0, 814, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), NoteFieldDisplay = "Back", NoteFieldName = "Back", NoteTypeID = 1, SequenceID = 2 }
                    );
                });

            modelBuilder.Entity("Oboete.Database.Entity.NoteTypeFieldValue", b =>
                {
                    b.Property<int>("NoteTypeFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("ModifiedDateTime");

                    b.Property<int>("NoteId");

                    b.Property<int>("NoteTypeFieldDefinitionId");

                    b.Property<string>("NoteValue");

                    b.HasKey("NoteTypeFieldValueId");

                    b.HasIndex("NoteId");

                    b.HasIndex("NoteTypeFieldDefinitionId");

                    b.ToTable("NoteTypeFieldValue");
                });

            modelBuilder.Entity("Oboete.Database.Entity.Flashcard", b =>
                {
                    b.HasOne("Oboete.Database.Entity.FlashcardTemplate", "FlashcardTemplate")
                        .WithMany()
                        .HasForeignKey("FlashcardTemplateID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oboete.Database.Entity.Note", "Note")
                        .WithMany("Flashcards")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oboete.Database.Entity.FlashcardTemplate", b =>
                {
                    b.HasOne("Oboete.Database.Entity.NoteType", "NoteType")
                        .WithMany("FlashcardTemplates")
                        .HasForeignKey("NoteTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Oboete.Database.Entity.Note", b =>
                {
                    b.HasOne("Oboete.Database.Entity.Deck", "Deck")
                        .WithMany("Notes")
                        .HasForeignKey("DeckID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oboete.Database.Entity.NoteType", "NoteType")
                        .WithMany()
                        .HasForeignKey("NoteTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oboete.Database.Entity.NoteTypeFieldDefinition", b =>
                {
                    b.HasOne("Oboete.Database.Entity.NoteType", "NoteType")
                        .WithMany("NoteFields")
                        .HasForeignKey("NoteTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Oboete.Database.Entity.NoteTypeFieldValue", b =>
                {
                    b.HasOne("Oboete.Database.Entity.Note", "Note")
                        .WithMany("NoteValues")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oboete.Database.Entity.NoteTypeFieldDefinition", "NoteTypeFieldDefinition")
                        .WithMany()
                        .HasForeignKey("NoteTypeFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
